name: Tests

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Setup DB
      run: |
        python3 ./app/manage.py makemigrations
        python3 ./app/manage.py migrate
    - name: Linting
      run: |
        flake8
    - name: Coverage report and testing
      run: |
        pip install coverage
        coverage run --parallel-mode --source='app' --omit="./app/manage.py,./*/migrations/*" ./app/manage.py test
        coverage report
