name: Tests

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Prerequisites
      run: |
        sudo apt-get install libpq-dev
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Linting
      run: |
        flake8
    - name: Coverage report and testing
      env:
        DB_HOST: postgres
        DB_NAME: postgres
        DB_USER: postgres
        DB_PASS: postgres
      run: |
        pip install coverage
        coverage run --omit="manage.py,./*/migrations/*" manage.py test
        coverage report
